<?php
/**
 * Implements hook_preprocess_html() for html templates.
 */
function callbackkiller_preprocess_html(&$variables)
{
	$config = \Drupal::config('callbackkiller.settings');
	$js = [
        '#tag' => 'script',
                '#attributes' => [
                    'type' => 'text/javascript',
                    'src' => 'https://cdn.envybox.io/widget/cbk.js?wcb_code=' . $config->get('callbackkiller_code'),
                    'charset' => "UTF-8",
                    'async' => true,
                ],
            ];
            $css = [
                '#tag' => 'link',
                '#attributes' => [
                    'rel' => 'stylesheet',
                    'href' => 'https://cdn.envybox.io/widget/cbk.css',
                ],
            ];
            $variables['page']['#attached']['html_head'][] = [$js, 'js'];
            $variables['page']['#attached']['html_head'][] = [$css, 'css'];
}